INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000000'::int, 'All Off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000001'::int, 'Diffractometer On, Detector Off, Robot Off, no air rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000010'::int, 'Illegal State: All off with air rights taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000011'::int, 'Diffractometer On, Detector Off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000100'::int, 'Illegal State: Detector Off and Ready');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000101'::int, 'Illegal State: Detector Off and Ready (Diffractometer On w/o Air rights)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000110'::int, 'Illegal State: Detector Off and Ready: Air rights taken but robot and diffractometer off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'000111'::int, 'Illegal State: Detector Off and Ready (Diffractomenter On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001000'::int, 'Illegal State: Exposing with diffractomenter and detector off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001001'::int, 'Illegal State: Exposing with detector off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001010'::int, 'Illegal State: Exposing with diffractomenter and detector off, Air rights taken (by whom?)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001011'::int, 'Illegal State: Exposing with detector off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001100'::int, 'Illegal State: Exposing with diffractometer off, detector off and ready?');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001101'::int, 'Illegal State: Detector off and ready?');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001110'::int, 'Illegal State: Detector off and ready. Diffractometer off and exposing');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'001111'::int, 'Illegal State: Detector off and ready.');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010000'::int, 'Diffractometer Off, Detector On but not ready, Robot Off, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010001'::int, 'Diffractometer On, Detector On but not ready, Robot Off, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010010'::int, 'Illegal State: Diffractometer Off, Detector On but not ready, Robot Off, Air Rights Taken (by whom?)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010011'::int, 'Diffractometer On, Detector On but not ready, Robot Off, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010100'::int, 'Diffractometer Off, Detector On and ready, Robot Off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010101'::int, 'Diffractometer On, Detector On and ready, Robot Off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010110'::int, 'Illegal State Diffractometer Off, Detector On and ready, Robot Off, Air Rights Taken (by whom?)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'010111'::int, 'Diffractometer On, Detector On and ready, Robot Off, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011000'::int, 'Diffractometer Off, Detector On and ready, Robot off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011001'::int, 'Diffractometer On, Detector On and ready, Robot off, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011010'::int, 'Illegal State: Diffractometer Off, Detector On and ready, Robot off, Air Rights Taken (by whome?)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011011'::int, 'Diffractometer On, Detector On and ready, Robot off, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011100'::int, 'Illegal State: Diffractometer Off but exposing, Detector On and ready, Robot off');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011101'::int, 'Diffractometer On, Detector On and ready, Robot off, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011110'::int, 'Illegal State: Diffractometer Off but exposing, Detector On and ready, Robot off, Air Rights Taken (by whom)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'011111'::int, 'Diffractometer On and preparing to expose, Detector On and ready, Robot off, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100000'::int, 'Diffractometer Off, Detector Off, Robot On');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100001'::int, 'Diffractometer On, Detector Off, Robot On, no air rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100010'::int, 'Diffractometer Off, Detector Off, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100011'::int, 'Diffractometer On, Detector Off,Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100100'::int, 'Illegal State: Detector Off and Ready (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100101'::int, 'Illegal State: Detector Off and Ready (Diffractometer On w/o Air rights), Robot On');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100110'::int, 'Illegal State: Detector Off and Ready, Diffractometer off, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'100111'::int, 'Illegal State: Detector Off and Ready (Diffractomenter On, Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101000'::int, 'Illegal State: Exposing with diffractomenter and detector off (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101001'::int, 'Illegal State: Exposing with detector off (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101010'::int, 'Illegal State: Exposing with diffractomenter and detector off, (Robot On and probably has the air rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101011'::int, 'Illegal State: Exposing with detector off (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101100'::int, 'Illegal State: Exposing with diffractometer off, detector off and ready? (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101101'::int, 'Illegal State: Detector off and ready? (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101110'::int, 'Illegal State: Detector off and ready. Diffractometer off and exposing (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'101111'::int, 'Illegal State: Detector off and ready.  (Robot On)');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110000'::int, 'Diffractometer Off, Detector On but not ready, Robot On, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110001'::int, 'Diffractometer On, Detector On but not ready, Robot On, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110010'::int, 'Diffractometer Off, Detector On but not ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110011'::int, 'Diffractometer On, Detector On but not ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110100'::int, 'Diffractometer Off, Detector On and ready, Robot On');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110101'::int, 'Diffractometer On, Detector On and ready, Robot On');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110110'::int, 'Diffractometer Off, Detector On and ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'110111'::int, 'Diffractometer On, Detector On and ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111000'::int, 'Diffractometer Off, Detector On and ready, Robot on');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111001'::int, 'Diffractometer On, Detector On and ready, Robot On, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111010'::int, 'Diffractometer Off, Detector On and ready, Robot off, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111011'::int, 'Diffractometer On, Detector On and ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111100'::int, 'Illegal State: Diffractometer Off but exposing, Detector On and ready, Robot On');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111101'::int, 'Diffractometer On, Detector On and ready, Robot On, No Air Rights');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111110'::int, 'Illegal State: Diffractometer Off but exposing, Detector On and ready, Robot On, Air Rights Taken');
INSERT INTO px.lockstates (lsstate,lstext) VALUES (b'111111'::int, 'Diffractometer On and preparing to expose, Detector On and ready, Robot On, Air Rights Taken');
