#! /bin/bash

# make sure the marccd/log file is writable
sudo /usr/local/bin/fixMarccdLog

# kill off any stray pxMarServer processes
sudo /usr/bin/killall -q pxMarServer.py

# wait for a gracefull exit
sleep 2

# kill off any stray pxMarServer processes, make sure they are dead
sudo /usr/bin/killall -q -s KILL pxMarServer.py

. /home/marccd/marccd_setup.sh

xrdb -merge <<EOF
Marccd*Stop*background: grey80
Marccd*Stop*foreground: grey80
Marccd*Stop*Sensitive: False
Marccd*ShutterMenuBar*background: grey80
Marccd*ShutterMenuBar*foreground: grey80
Marccd*ShutterMenuBar*Sensitive: False
EOF

currentuser=`psql -qAn --pset tuples_only -h 10.1.0.3 -U lsuser -c "select * from px.whoami()" ls`
iam=`whoami`

if [[ "ZZ"$currentuser != "ZZ"$iam ]]; then    
    if [[ "ZZ"$currentuser == "ZZ" ]]; then
	zenity --warning --title="Marccd Startup Warning"  --text "No one is logged into the MD2.  Are you sure you want to continue?"
	if [ $? -ne 0 ]; then
	    exit
	fi
    else
	zenity --error --title="Marccd Startup Error"  --text "$currentuser is logged in to the MD2 but you are $iam"
	exit
    fi
fi

cd ~
/home/marccd/bin/linux/marccd -rf



